### ISSUE TITLE
The plugin seem totally broken

### ISSUE THREAD

**Issue by antoine-pous** [NicolasSiver/nodebb-plugin-ns-twitch-monitor#10]
I run on NodeBB 1.4.5 and the plugin seem broken.

The current configuration doesn't work and i have no more access to the plugin settings.

Can you follow the real NodeBB compatibility instead of using `^1.x` in package.json?

**Comment by NicolasSiver** [comment]
By semver, every minor or patch version should be backward compatible. Technically plugin should not work with NodeBB 2.x.x.

The plugin was Ok with 1.4.4 where 1.4.5 just a patch version.

**Comment by NicolasSiver** [comment]
What error do you have in NodeBB logs?

**Comment by antoine-pous** [comment]
I haven't log, but the route to `admin/plugins/twitch-monitor` is broken and i haven't the plugin in ACP menu.

**Comment by antoine-pous** [comment]
Oh, in the console i have a warning:

```
Error has occurred, can not update initial cache for twitch monitor, error: [[error:invalid-event]]
(anonymous) @ nodebb.min.js:23
```

**Comment by antoine-pous** [comment]
Without any reason, the plugin display channels now, but i have some REDIS error.

```console
node_redis: Deprecated: The HMSET command contains a "null" argument.
This is converted to a "null" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
```

**Comment by NicolasSiver** [comment]
If you disable Twitch plugin, do you still see redis error?

**Comment by antoine-pous** [comment]
No, the errors desapear when i turn it off.

**Comment by NicolasSiver** [comment]
The plugin uses internal NodeBB wrappers for work with Database (Mongo or Redis).
I'm not sure how actionable an issue from the plugin perspective.
