### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by KazeroG** [NicolasSiver/nodebb-plugin-ns-twitch-monitor#3]
hello mate 

sorry i newer so iam searching how we use this ? i dont even know if it exe app or web app O_O plz need help 

thanks for helping hope that can help other to !!

**Comment by NicolasSiver** [comment]
It's a plugin for NodeBB forum, which is a forum software written on NodeJs.
You can get more details on official community board - https://community.nodebb.org

**Comment by KazeroG** [comment]
thanks very much for information !
