### ISSUE TITLE
'Mod on _id not allowed' when trying to add channel

### ISSUE THREAD

**Issue by Niller2005** [NicolasSiver/nodebb-plugin-ns-twitch-monitor#5]
I have added a client ID from twitch, but when i add a channel it pops up with a little black box in the bottom left corner, and sents me to the settings tab.

**Comment by NicolasSiver** [comment]
> `Mod on _id not allowed`

Is this a message at notification? (black box at the bottom-left)?

**Comment by Niller2005** [comment]
http://puu.sh/pmyKC/7d13a89582.png

**Comment by NicolasSiver** [comment]
What is the channel's name?

**Comment by Niller2005** [comment]
niller2005

**Comment by NicolasSiver** [comment]
<img width="502" alt="screen shot 2016-06-12 at 9 09 04 am" src="https://cloud.githubusercontent.com/assets/135263/15991314/6eb65c8e-307d-11e6-8c4c-91ceb1466a8f.png">

Performed Add and Remove of the channel several times, I don't have any issue with your channel.
Did you specify correctly API Key?
What database do you use - MongoDB or Redis?

**Comment by Niller2005** [comment]
I have `https://forum.longhairdontcare.eu/admin/plugins/twitch-monitor` in the Redirect URI.
And I just took the client ID it gave me and copy pasted it.

I use mongoDB

**Comment by NicolasSiver** [comment]
I think I have found an issue with this warning.
Don't remember such thing, when did an initial development of the plugin, but some sanitization should be made on responses from Twitch.

And in your case It relates to #4 ticket, while It's successfully creates sorted ID for the record, It isn't possible to store a payload for the Twitch's response.
