### ISSUE TITLE
Error causing NodeBB to crash

### ISSUE THREAD

**Issue by frodesigns** [NicolasSiver/nodebb-plugin-ns-twitch-monitor#7]
8/9 19:09 [25702] - [31merror[39m: TypeError: Cannot read property 'forEach' of undefined
    at /node_modules/nodebb-plugin-ns-twitch-monitor/plugin/twitch/api.js:74:36

**Comment by NicolasSiver** [comment]
Interesting. Technically, you didn't receive proper response from the Twitch for whatever reason.
