### ISSUE TITLE
No update button on Client ID

### ISSUE THREAD

**Issue by JoshRickers** [NicolasSiver/nodebb-plugin-ns-twitch-monitor#9]
Adding a client ID displays no update button to save the settings.
I am unable to add the client ID.

NodeBB v 1.0.2

**Comment by NicolasSiver** [comment]
There is no `save` button, it will be red/green if you hit `Enter` or remove focus from the field.

**Comment by NicolasSiver** [comment]
But I understand possible confusion. In future update I will look at a possible change.

**Comment by JoshRickers** [comment]
Oh OK, my bad!

Mine was staying red when I added in my app ID, has the format changed?

Would this be because i am not on the latest version of NodeBB?

**Comment by NicolasSiver** [comment]
It could be Twitch. They have released a new version of API.
There is a big possibility that something does not work anymore.

**Comment by NicolasSiver** [comment]
UX is updated for the Client ID. Now It should be easier to work with Client ID.

<img width="209" alt="screen shot 2016-12-11 at 5 01 27 pm" src="https://cloud.githubusercontent.com/assets/135263/21083709/679ef7e0-bfc4-11e6-8eba-0235c06524b8.png">
